// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7I-bUVYfdY9PcUD9kMD4In7Qval45ZEE',
    appId: '1:426798853994:web:91a1ff076225712466ff13',
    messagingSenderId: '426798853994',
    projectId: 'fitfuel-ab042',
    authDomain: 'fitfuel-ab042.firebaseapp.com',
    storageBucket: 'fitfuel-ab042.firebasestorage.app',
    measurementId: 'G-JE5FL22S10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_6YUgjJJI9vdZ6EJ_ReUjfNOUSIhxwT8',
    appId: '1:426798853994:android:17c7788a7f8ce0ec66ff13',
    messagingSenderId: '426798853994',
    projectId: 'fitfuel-ab042',
    storageBucket: 'fitfuel-ab042.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzEUBT7OsIzCxW46d17aK9gp8hw4OJCUM',
    appId: '1:426798853994:ios:3bb4bc01d7955aa066ff13',
    messagingSenderId: '426798853994',
    projectId: 'fitfuel-ab042',
    storageBucket: 'fitfuel-ab042.firebasestorage.app',
    iosBundleId: 'com.example.fitfuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzEUBT7OsIzCxW46d17aK9gp8hw4OJCUM',
    appId: '1:426798853994:ios:3bb4bc01d7955aa066ff13',
    messagingSenderId: '426798853994',
    projectId: 'fitfuel-ab042',
    storageBucket: 'fitfuel-ab042.firebasestorage.app',
    iosBundleId: 'com.example.fitfuel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7I-bUVYfdY9PcUD9kMD4In7Qval45ZEE',
    appId: '1:426798853994:web:a5b49e815ff1463c66ff13',
    messagingSenderId: '426798853994',
    projectId: 'fitfuel-ab042',
    authDomain: 'fitfuel-ab042.firebaseapp.com',
    storageBucket: 'fitfuel-ab042.firebasestorage.app',
    measurementId: 'G-LTGSGSHLV8',
  );
}
